### ISSUE TITLE
AutoCloseable or close functionality on TimeoutManager or MessageStream

### ISSUE THREAD

**Issue by leozilla** [Domo42/saga-lib#13]
The default implementation InMemoryTimeoutManager of the TimeoutManager contains an executor which should be shutdown if the MessageStream is no longer in use but there is no way to do this currently.
Its also akward to get to the TimeoutManager instance itself, you almost always have to provide your own TimeoutManager to control the Scheduler (which brings me to the next issue).

It would be better to have some way to shutdown the MessageStream either via an explicit close, shutdown method or at least provide such a method on the TimeoutManager interface.

**Comment by Domo42** [comment]
Good point, having an explicit close method is a good idea. While my expectation is that the saga-lib steam will basically be running as long as the application runs, this might not always be case.

Just for reference the saga-lib creates as well a single daemon thread by default for handling messages provided via the add() method. This one would be automatically be closed via application shutdown, but not when the saga-lib needs opening and closing during runtime.
