### ISSUE TITLE
ModulesInvoker swallows Exceptions (including InterruptedException) without rethrowing after Modules invoked

### ISSUE THREAD

**Issue by leozilla** [Domo42/saga-lib#16]
There is one problem with the new way of handling `onError `and `onFinished `of the SagaModules.

1. The ModulesInvoker#finish() method does swallow all exceptions without rethrowing any exception thrown by SagaModule#onFinished after all onFinished methods where invoked.
This has quite some implications in my case because as a caller of the MessageStream I now don't get any information back if a message handling did succeed or not.
I really need a way to handle this kind of errors.

2. if SagaModules onFinished or onError method throws an InterruptedException the ModuleInvoker catches it and does not restore the interrupted state.

```
public void finish() {
   // swallows all exceptions and does not rethrow any of them!
   Lists.reverse(finishers).forEach(Runnable::run);
}
```

```
private static void tryExecute(final Runnable runnable, final SagaModule module) {
        try {
            runnable.run();
        } catch (Exception ex) {
            // swallows InterruptedException!
            LOG.error("Error executing function on module {}", module, ex);
        }
    }
```

**Comment by Domo42** [comment]
Mmm ... this needs a little bit more thought. Now every _onFinished_ handler gets executed, regardless of exceptions in other handlers. This also means that there might be a whole list of exceptions for each handler. But of course after the finish handler i can only do a single throw.

My suggestion would be to introduce a separate exception type that can be used as a container for a list of errors that occurred during handling. For example there might be one, during saga handling and then another one in the module finish handlers.

If there's just a single error the original exception is re-thrown. In case of a whole list of error events, these would be collected and thrown as a the new exception type.
