### ISSUE TITLE
wiki typos

### ISSUE THREAD

**Issue by birbilis** [Domo42/saga-lib#27]
A) at
https://github.com/Domo42/saga-lib/wiki/Sagas

1. "Please not that there is no timeout handling" should say "Please note"
2. "First we needs" should be "First we need"
3. "from either AbstractSaga order AbstractSingleEventSaga" should be "from either AbstractSaga or AbstractSingleEventSaga"
4. "When needed needed" should be "When needed"

------

B) at
https://github.com/Domo42/saga-lib/wiki/HandlerDescription

1. "There are additional helpers in the for of the AbstractHandler and AbstractAutoTypedHandler classes" should say "in the form of"
2. "In comparison the the AbstractSingleEventSaga" should say "In comparison to the"

------

C) at
https://github.com/Domo42/saga-lib/wiki/Timeouts 

1. "public void oderProduct(final OrderRequest request)" should say "orderProduct"
 
------

D) at
https://github.com/Domo42/saga-lib

1. "This saga is using annoations" should say "annotations"

**Comment by Domo42** [comment]
Thanks a lot, I've updated the markdowns.
