### ISSUE TITLE
Support for Custom Saga Matcher Strategies

### ISSUE THREAD

**Issue by leozilla** [Domo42/saga-lib#6]
In some scenarios I would like to have better control over the state lookup and exactly when a handler invocation takes place in the sagaLib. I know there are already the Interceptors but they dont allow me to fine tune the state lookup.

When I know based on the type or execution context what lookup I need to do I can save some time and warning logs be explicitly specifying them.

This can also be helpful when I do want to use my own Timeout class and not the one already provided by the sagaLib but I would like to have the same saga instance lookup mechanism as the sagaLib already uses for its internal Timeouts.

Also for other use cases I might already know how to find a certain saga.
Therefor it would be nice to specify a "custom saga instance matcher strategy" when configuring the MessageStream (and maybe also a method to overwrite them later on).

This Strategy (or maybe Strategies) should provide me a way to decide which saga(s) I want to invoke based on:
* The message type
* The current exection context (which could be a nested context)
* The current executing saga and its state (only in the case of nested execution)
* Maybe also other factors ...

The reason for this is to have more control over which saga handler(s) are invoked and when a (maybe expensiv e) call to the StateStorage is made.

**Comment by Domo42** [comment]
Merged into master, there is now a StrategyFinder that can be replaced or overwritten.
