### ISSUE TITLE
Java 8 + new org.reflections + TimeoutManager enhancement

### ISSUE THREAD

**Issue by leozilla** [Domo42/saga-lib#7]
I have extended the following things in a patch

TimeoutManager
* provided ExecutionContext in requestTimeout and cancelTimeout
* returned TimeoutId when requesting timeout
* added cancelTimeout for specific timeoutId

Updated to Java 8 and org.reflections 0.9.10

Where can I upload the patch?

**Comment by Domo42** [comment]
usually by providing a pull request

However, some of the stuff you mention is already part of the latest snapshot

**Comment by Domo42** [comment]
I'm closing this issue, If you wan't something merged into the base lib, please provide a pull request. This has the benefit that your commits become part of the git history and your work is properly attributed.
