### ISSUE TITLE
Make TimeoutId an interface to allow custom implementations

### ISSUE THREAD

**Issue by leozilla** [Domo42/saga-lib#9]
The TimeoutId type could be an interface so that a TimeoutManager implementation can choose a suitable implementation.
Implementations could be UUTimeoutId, StringTimeoutId and NumericTimeoutId.

When storing the timeout state in a (distributed) database you could use the db key as the TimeoutId.

**Comment by Domo42** [comment]
already done with the lastest commit 0902b5a in the master branch

**Comment by Domo42** [comment]
implemented in master branch
